require("johhnry.filetypes")
require("johhnry.options")
require("johhnry.keymaps")

require("johhnry.lazy")

require("johhnry.colorscheme")
require("johhnry.statusline")
require("johhnry.cmp")
require("johhnry.lsp")
require("johhnry.telescope")
require("johhnry.treesitter")
require("johhnry.nvim-tree")
require("johhnry.which-key")
require("johhnry.project")
require("johhnry.toggleterm")
require("johhnry.autopairs")
require("johhnry.comment")
require("johhnry.gitsigns")
require("johhnry.bufferline")
